MovieShop/MovieShopMVC/Models/ErrorViewModel.cs
using System;

namespace MovieShopMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MovieShop/MovieShopMVC/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ApplicationCore.Models;
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;

namespace MovieShopMVC.Controllers
{
    public class AccountController : Controller
    {
        private readonly IUserService _userService;

        public AccountController(IUserService userservice)
        {
            _userService = userservice;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(UserRegisterRequestModel model)
        {
            var user = await _userService.RegisterUser(model);
            return RedirectToAction("Login");
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(UserLoginRequestModel requestmodel)
        {
            var user = await _userService.ValidateUser(requestmodel);
            // redirect to home page

            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Email, user.Email),
                new Claim(ClaimTypes.GivenName, user.FirstName),
                new Claim(ClaimTypes.Surname, user.LastName),
                new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
                new Claim(ClaimTypes.DateOfBirth, user.DateOfBirth.ToString())
            };
            foreach(var role in user.Roles)
            {
                claims.Add(new Claim("Roles", role.Name));
            }

            
            // identity object thats gonna use claims

            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            // create the cookie
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));
            return LocalRedirect("~/");
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("LogIn", "Account");
        }
    }    
}

MovieShop/MovieShopMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ApplicationCore.ServiceInterfaces;
using Infrastructure.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MovieShopMVC.Models;

namespace MovieShopMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly IMovieService _movieService;

        public HomeController(IMovieService movieService)
        {
            _movieService = movieService;
        }

       
        public IActionResult Privacy()
        {
            return View();
        } 
        
        public async Task<IActionResult> Index()
        {
            // it will look inside views folder =>  folder name with same nsame
            // as COntroller name and look for view with same name as action metjhod name 
            // i want to display top revenue movies
            // get model data

            // models.
            var movies = await _movieService.Get30HighestGrossingMovies();
            return View(movies);
        }




        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MovieShop/MovieShopMVC/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Infrastructure.Services;
using ApplicationCore.ServiceInterfaces;
using ApplicationCore.Models;

namespace MovieShopMVC.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieService _movieService;
        public MoviesController(IMovieService movieService)
        {
            _movieService = movieService;
        }

        public async Task<IActionResult> Details(int id = 1)
        {

            var movie = await _movieService.GetMovieDetailsById(id);

            return View(movie);
        }

        public async Task<IActionResult> Genre(int id =1 ,int page =1)
        {
            var movies = await _movieService.GetMoviesByGenreId(id);
            var moviesView = new MovieViewModel
            {
                MoviePerPage = 30,
                GenreId = id,
                Movies = movies,
                CurrentPage = page
            };
            return View(moviesView);
        }

        public async Task<IActionResult> TopRated()
        {
            var movies = await _movieService.GetTopRatedMovies();
            return View(movies);
        }
   
    }
}

MovieShop/MovieShopMVC/Controllers/UserController.cs
using ApplicationCore.Models;
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
namespace MovieShopMVC.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly ICurrentUserService _currentUserService;
        public UserController(IUserService userService, ICurrentUserService currentUserService)
        {
            _userService = userService;
            _currentUserService = currentUserService;
        }
        // showing list of movies
        // Filters
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Purchases()
        {
            var userId = _currentUserService.UserId;
            var purchases = await _userService.GetPurchasedMoviesByUserId(userId);
            // call the User Service to get movies purchased by user, and send the data to the view, and use the existing MovieCard Partial View
            return View(purchases);
        }




        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Favorites()
        {
            var userId = _currentUserService.UserId;
            var favorites = await _userService.GetFavoriteMoviesByUserId(userId);
            // call the User Service to get movies favorited by user, and send the data to the view, and use the existing MovieCard Partial View
            return View(favorites);
        }
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Details()
        {

            var email = _currentUserService.Email;
            var user = await _userService.GetUserDetailsByEmail(email);
            user.FullName = _currentUserService.FullName;

            // call the User Service to get User Details and dispaly in a View
            // get user id from httpcontext and send it to user services
            return View(user);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit()
        {
            var email = _currentUserService.Email;
      
            var user = await _userService.GetUserEditInformation(email);

            return View(user);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(UserEditRequestModel model)
        {
            var user = await _userService.UpdateUserInformation(model);
            return RedirectToAction("Logout", "Account");
        }
    }
}

MovieShop/MovieShopMVC/ViewComponents/HeaderViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using ApplicationCore.RepositoryInterfaces;
using ApplicationCore.ServiceInterfaces;

namespace MovieShopMVC.ViewComponents
{
    public class HeaderViewComponent:ViewComponent
    {
        private readonly IGenreService _genreService;
        public HeaderViewComponent(IGenreService genreService)
        {
            _genreService = genreService;
        }
        
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var genres = await _genreService.ListAllGenresAsync();
            return View(genres);
        }

    }
}

MovieShop/MovieShopMVC/Views/Home/Index.cshtml
@model IEnumerable<ApplicationCore.Models.MovieCardResponseModel>

@{
    ViewData["Title"] = "Home Page";
}

<div class="rounded">
    <div class="container-fluid">
        <div class="row">
            @foreach(var movie in Model)
            {
                <div class="col-xl-2 col-sm-4 col-lg-3">
                    @*call partial view from here and send the movie info object to partial view*@
                    <partial name="_MovieCard" model="movie"/>
                </div>
            }
        </div>
    </div>
</div>



   

MovieShop/MovieShopMVC/Views/Movies/Details.cshtml
@model ApplicationCore.Models.MovieDetailsResponseModel

<div class="container-fluid">
    
    <div class="card" >
        <div class="container-fluid bg-dark" style="max-height: 600px;overflow: hidden; ">
            <img src="@Model.BackdropUrl" class="img-fluid" alt="@Model.Title" />
        </div>
        
        <div class="card-img-overlay" style="background: rgba(0, 0, 20, 0.7);">
            <div class="row">
                <div class="col-4">
                    <img src="@Model.PosterUrl" class="img-fluid float-right" />
                </div>
                <div class="col-5">
                    <div style="padding-left: 100px">
                        <div class="row">
                            <div class="col">
                                <h1 class="text-light">@Model.Title</h1>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <h6 class="text-secondary">@Model.Tagline</h6>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-4">
                                <p class="text-secondary font-weight-bold">@Model.RunTime.ToString() m | @Model.ReleaseDate.GetValueOrDefault().Year</p>
                            </div>
                            <div class="col-8">
                                @if (@Model.Genres != null)
                                {
                                    foreach (var genre in @Model.Genres)
                                    {
                                        <span class="badge rounded-pill bg-secondary text-light"><a asp-controller="Movies" asp-action="Genre" asp-route-id="@genre.Id" style="text-decoration: none;color: inherit">@genre.Name</a></span>
                                    }
                                }
                                else
                                {
                                    <span class="badge rounded-pill bg-light text-dark">No Genre</span>
                                }
                            </div>
                        </div>
                        <div class="row py-2">
                            <div class="col">
                                @if (@Model.Rating != 0.0m)
                                {
                                    <h5><span class="badge bg-success text-light">@Math.Round(Model.Rating.GetValueOrDefault(), 1)</span></h5>
                                }
                                else
                                {
                                    <h5><span class="badge bg-success text-light">No Rating</span></h5>
                                }
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <p class="text-light">@Model.Overview</p>
                            </div>
                            
                        </div>
                    </div>
                </div>
                <div class="col-3 ">
                    <div class="row justify-content-end mt-5 mr-4 pt-5 pl-5" >
                        <button type="button" class="btn btn-outline-light btn-block"><i class="far fa-edit"></i> Review</button>
                    </div>
                    <div class="row justify-content-end mt-4 mr-4 pl-5">
                        <button type="button" class="btn btn-light float-right btn-block">BUY $@Model.Price</button>
                    </div>
                    
                </div>
            </div>
        </div>

    </div>
    <div class="row pt-3">
        <div class="col-4 bg-light">
            <div id="movieFacts">
                <h6>MOVIE FACTS</h6>
                <ul class="list-group list-group-flush mb-2">
                    <li class="list-group-item" style="background-color:inherit"><i class="far fa-calendar-alt"></i> Release Date <span class="badge badge-pill bg-dark text-light">@Model.ReleaseDate.GetValueOrDefault().ToString("MMM dd, yyyy")</span></li>
                    <li class="list-group-item" style="background-color:inherit"><i class="fas fa-hourglass-half"></i> Run Time <span class="badge badge-pill bg-dark text-light">@Model.RunTime m</span></li>
                    <li class="list-group-item" style="background-color:inherit"><i class="far fa-money-bill-alt"></i> Box Office <span class="badge badge-pill bg-dark text-light">$@Math.Round(Model.Revenue.GetValueOrDefault(), 2).ToString("N")</span></li>
                    <li class="list-group-item" style="background-color:inherit"><i class="fas fa-dollar-sign"></i> Budget <span class="badge badge-pill bg-dark text-light">$@Math.Round(Model.Budget.GetValueOrDefault(), 2).ToString("N")</span></li>
                    <li class="list-group-item" style="background-color:inherit">
                        <a href="@Model.ImdbUrl" style="color:inherit;"><i class="fab fa-imdb"></i></a>&nbsp;
                        <a href="#" style="color:inherit;"><i class="fas fa-share-square"></i></a>
                    </li>
                </ul>
                
            </div>
            <div id="trailers" class="pt-3">
                <h6>TRAILERS</h6>
                <ul class="list-group list-group-flush">
                    @if (@Model.Trailers != null)
                    {
                        foreach (var trailer in @Model.Trailers)
                        {
                            <li class="list-group-item" style="background-color:inherit"><a href="@trailer.TrailerUrl" style="text-decoration:none;color:inherit;"><i class="fab fa-youtube"></i> @trailer.Name</a> </li>
                        }
                    }
                    else
                    {
                        <li class="list-group-item">No Trailer</li>
                    }
                </ul>
            </div>
            
        </div>
        <div class="col-5">
            <div id="cast" style="padding-left: 100px">
                <h6>CAST</h6>
                <ul class="list-group list-group-flush">
                    @if (@Model.Casts != null)
                    {
                        @foreach (var cast in @Model.Casts)
                        {
                            <li class="list-group-item">
                                <div class="row">
                                    <div class="col-2">
                                        <img src="@cast.ProfilePath" class="d-inline rounded-circle" width="45" height="65" />
                                    </div>
                                    <div class="col-5">
                                        <span>@cast.Name</span>
                                    </div>
                                    <div class="col-5">
                                        <span>@cast.Character</span>
                                    </div>
                                </div>
                                
                                
                                
                            </li>
                        }
                    }
                    else
                    {
                        <li class="list-group-item">No Cast</li>
                    }
                </ul>
            </div>
            
        </div>
        <div class="col-3">

        </div>

    </div>
</div>

MovieShop/MovieShopMVC/Views/Movies/Genre.cshtml
@model ApplicationCore.Models.MovieViewModel

@{
    ViewData["Title"] = "Genre";
}

<div class="rounded">
    <div class="container-fluid">
        <div class="row">
            @foreach (var movie in @Model.PaginatedMovies())
            {
                <div class="col-xl-2 col-sm-4 col-lg-3">
                    @*call partial view from here and send the movie info object to partial view*@
                    <partial name="_MovieCard" model="movie" />
                </div>
            }
        </div>

        <ul class="pagination">
            <li class="page-item">
                <a class="page-link" asp-controller="Movies" asp-action="Genre" asp-route-id="@Model.GenreId" asp-route-page="1">
                    &laquo;&laquo;
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" asp-controller="Movies" asp-action="Genre" asp-route-id="@Model.GenreId" asp-route-page="@(Model.CurrentPage > 1 ? Model.CurrentPage - 1 : 1)">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            @if (Model.CurrentPage > 4)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="Movies" asp-action="Genre" asp-route-id="@Model.GenreId" asp-route-page="1">
                        1
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="">
                        ...
                    </a>
                </li>
            }

            @if (Model.CurrentPage >= Model.PageCount() - 3)
            {
                for (int i = 0; Model.CurrentPage <= Model.PageCount() && i < 5; i++)
                {
                    <li class="@(Model.PageCount()-4 + i == Model.CurrentPage ? "page-item active" : "page-item")">
                        <a class="page-link" asp-controller="Movies" asp-action="Genre" asp-route-id="@Model.GenreId" asp-route-page="@(Model.PageCount()-4 + i)">@(Model.PageCount() - 4 + i)</a>
                    </li>
                }
            }
            else if (Model.CurrentPage <= 4)
            {
                @for (int i = 0; Model.CurrentPage <= Model.PageCount() && i < 5; i++)
                {
                    <li class="@(i == Model.CurrentPage-1 ? "page-item active" : "page-item")">
                        <a class="page-link" asp-controller="Movies" asp-action="Genre" asp-route-id="@Model.GenreId" asp-route-page="@(i+1)">@(i+1)</a>
                    </li>
                }
            }
            else
            {
                for (int i = 0; Model.CurrentPage <= Model.PageCount() && i < 5; i++)
                {
                    <li class="@(i == 2  ? "page-item active" : "page-item")">
                        <a class="page-link" asp-controller="Movies" asp-action="Genre" asp-route-id="@Model.GenreId" asp-route-page="@(Model.CurrentPage - 2 + i)">@(Model.CurrentPage - 2 + i)</a>
                    </li>
                }
            }
            @if (Model.CurrentPage <= Model.PageCount() - 4)
            {
                <li class="page-item">
                    <a class="page-link" href="">
                        ...
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-controller="Movies" asp-action="Genre" asp-route-id="@Model.GenreId" asp-route-page="@Model.PageCount()">
                        @Model.PageCount()
                    </a>
                </li>
            }


            <li class="page-item">
                <a class="page-link" asp-controller="Movies" asp-action="Genre" asp-route-id="@Model.GenreId" asp-route-page="@(Model.CurrentPage+1)">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" asp-controller="Movies" asp-action="Genre" asp-route-id="@Model.GenreId" asp-route-page="@Model.PageCount()">
                    &raquo;&raquo;
                </a>
            </li>

        </ul>
  
    </div>
</div>

MovieShop/MovieShopMVC/Views/Movies/GetTopRevenueMovies.cshtml
@model List<ApplicationCore.Models.MovieCardResponseModel>;

@{
    ViewData["Title"] = "Home Page";
}

@foreach (var movie in Model)
{ 
    <div>
        @movie.Id
    </div>
    <div>
        @movie.PosterUrl
    </div>
}

MovieShop/MovieShopMVC/Views/Movies/TopRated.cshtml
@model IEnumerable<ApplicationCore.Models.MovieCardResponseModel>

@{
    ViewData["Title"] = "Top Rated Movies";
}

<div class="rounded">
    <div class="container-fluid">
        <div class="row">
            @foreach (var movie in Model)
            {
                <div class="col-xl-2 col-sm-4 col-lg-3">
                    @*call partial view from here and send the movie info object to partial view*@
                    <partial name="_MovieCard" model="movie" />
                </div>
            }
        </div>
    </div>
</div>

MovieShop/MovieShopMVC/Views/Shared/Components/Header/Default.cshtml
@model List<ApplicationCore.Models.GenreModel>

<header>
    <nav class="navbar navbar-expand-lg navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3 ">
        <div class="container-fluid">
            <a class="navbar-brand " asp-area="" asp-controller="Home" asp-action="Index">Movie Shop <i class="fas fa-film"></i></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1  mr-auto">
                    <li class="nav-item">
                        <div class="nav-itme dropdown">
                            <button class="btn btn-dark dropdown-toggle text-muted" type="button" id="genres" data-toggle="dropdown">
                                GENRES
                            </button>
                            <div class="dropdown-menu">
                                @foreach (var genre in Model)
                                {
                                    <a class="dropdown-item" asp-controller="Movies" asp-action="Genre" asp-route-id="@genre.Id">@genre.Name</a>
                                }

                                

                            </div>
                        </div>
                    </li>

                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="btn btn-dark border rounded-1" asp-controller="Account" asp-action="Login">
                            Login
                        </a>
                        <a class="btn btn-dark border rounded-1" asp-controller="Account" asp-action="Register">
                            Register
                        </a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
</header>

MovieShop/MovieShopMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieShopMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3 ">
            <div class="container-fluid">
                <a class="navbar-brand " asp-area="" asp-controller="Home" asp-action="Index">Movie Shop <i class="fas fa-film"></i></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1  mr-auto">
                        <li class="nav-item">
                            <div class="nav-itme dropdown">
                                <button class="btn btn-dark dropdown-toggle text-muted" type="button" id="genres" data-toggle="dropdown">
                                    GENRES
                                </button>
                                
                            </div>
                        </li>

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    @*@await Component.InvokeAsync("Header")*@
  
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MovieShopMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

MovieShop/MovieShopMVC/Views/Shared/_MovieCard.cshtml
@model ApplicationCore.Models.MovieCardResponseModel

<div class="card mb-4 shadow">
    <a asp-controller="Movies" asp-action="Details" asp-route-id="@Model.Id">
        <img src ="@Model.PosterUrl" class="card-img" alt="@Model.Id"/>
    </a>

</div>

MovieShop/MovieShopMVC/Views/Shared/_PurchaseDetailsCard.cshtml
  @model ApplicationCore.Models.PurchaseDetailsResponseModel

<div class="row justify-content-center">
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">Purchase Details</h5>
            <div class="row">
                <div class="col-2">
                    <img src="@Model.PosterUrl"/>
                </div>
                <div class="col-10">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            Purchase Date: @Model.PurchaseDateTime
                        </li>
                        <li class="list-group-item">
                            Price: @Model.TotalPrice
                        </li>
                        <li class="list-group-item">
                            Purchase Number: @Model.PurchaseNumber
                        </li>
                    </ul>
                </div>
            </div>
         
        </div>
    </div>
</div>

MovieShop/MovieShopMVC/Views/User/Details.cshtml
@model ApplicationCore.Models.UserDetailsResponseModel

<div class="row justify-content-center" >
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">@Model.FullName</h5>
            <h6 class="card-subtitle mb-2 text-muted">@Model.Email</h6>
            <p class="card-text">DOB: @(Model.DateOfBirth != null ? Model.DateOfBirth: "N/A") </p>
            <p class="card-text">Phone Number: @(Model.PhoneNumber!= null? Model.PhoneNumber: "N/A") </p>
            <p class="card-text">Two Factor: @(Model.TwoFactorEnabled != false ? "Enabled": "Disabled") </p>
        </div>
    </div>
</div>

MovieShop/MovieShopMVC/Views/User/Edit.cshtml
@model ApplicationCore.Models.UserEditRequestModel

@{
    ViewData["Title"] = "Edit";
}

<h1>View</h1>

<h4>UserEditRequestModel</h4>
<hr />
<div class="row justify-content-center">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="@Model.Id" class="control-label"></label>
                <input asp-for="@Model.Id" class="form-control" readonly />
                <span asp-validation-for="@Model.Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Email" class="control-label"></label>
                <input asp-for="@Model.Email" class="form-control" required />
                <span asp-validation-for="@Model.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Password" class="control-label"></label>
                <input asp-for="@Model.Password" class="form-control"  />
                <span asp-validation-for="@Model.Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.FirstName" class="control-label"></label>
                <input asp-for="@Model.FirstName" class="form-control"  required/>
                <span asp-validation-for="@Model.FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.LastName" class="control-label"></label>
                <input asp-for="@Model.LastName" class="form-control"  required/>
                <span asp-validation-for="@Model.LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.DateOfBirth" class="control-label"></label>
                <input asp-for="@Model.DateOfBirth" class="form-control" />
                <span asp-validation-for="@Model.DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Change" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}